= Redis Demonstration

This demonstration program focuses on using Redis for caching and lock management.

== Configuration Settings

The configuration is expressed in JSON and is supplied in config/config.json in the 'redis' section.

* *hostname* The name of the host that the Redis server is listening on
* *port* The number of the port that the Redis server is listening on
* *protocol* The protocol for the Redis connect string, typically "redis://"
* *server-cli*
** *command-intel* The fully qualified path name to the 'redis-server' command on Intel architectures
** *command-silicon* The fully qualified path name to the 'redis-server' command on Apple Silicon architectures
** *argument* The version argument for 'redis-server'

== Logging

Logging is achieved using the SLF4J facade over Logback. The logging configuration is supplied in config/logback.xml.

== Demonstrated Concepts

* Keys
* Object Holders (RBuckets)
* AtomicLock
* Topics
* Maps
* Sets
* Lists
* Locks
* Semaphores
* Countdown Latches
* JSON
* Live Objects
* Pipelining

== Resources

https://www.baeldung.com/redis-redisson
https://github.com/redisson/redisson/wiki/Table-of-Content
https://javadoc.io/doc/org.redisson/redisson/latest/index.html

=== Current version: 0.10.0.
